Neos:
  Neos:
    fusion:
      autoInclude:
        'Erk.Flow.FusionBase': true
  Fusion:
    defaultContext:
      'Erk.Flow.FusionBase.FlashMessages': Erk\Flow\FusionBase\Eel\Helper\FlashMessagesHelper
